world_positions: # measurements in meters
  names: ['C', 'M', 'A', 'B'] #, 'C1'] # F is on second row
  pos_x: [0.63, 0.63, 0.63, 0.757]
  pos_y: [0.21, -0.05, -0.31, -0.05] # 0.57 and 0.01 is the midpoint that works for both grippers!
  pos_z: [-0.05, -0.05, -0.05, -0.05, -0.05, -0.05]
  
world_objects: # measurements in meters
  names: ['entity', 'position', 'object', 'cube', 'base', 'roof']
  parents: ['', 'entity', 'entity', 'object', 'object', 'object']
  entity: [0.001, 0.001, 0.001]
  position: [0.05, 0.05, 0.005]
  object: [0.001, 0.001, 0.001]
  base: [0.1, 0.1, 0.04]
  cube: [0.04, 0.04, 0.03]
  roof: [0.023, 0.023, 0.03]
  #pillar: [0.035, 0.035, 0.07]
  variance: 0.075